ALTER TABLE sa_eleicoes.despesas_contratadas
ALTER COLUMN "DT_PRESTACAO_CONTAS" TYPE DATE 
USING TO_DATE("DT_PRESTACAO_CONTAS", 'DD/MM/YYYY');

ALTER TABLE sa_eleicoes.despesas_contratadas
ALTER COLUMN "VR_DESPESA_CONTRATADA" TYPE NUMERIC 
USING REPLACE("VR_DESPESA_CONTRATADA", ',', '.')::NUMERIC;

